name: segmentation-analysis

channels:
  - nvidia
  - conda-forge
  - defaults
  - pytorch
  - fvcore
  - iopath
  - pytorch3d

dependencies:
  - python=3.10
  - ipykernel
  - ffmpeg
  - nodejs
  - pip
  - pip:
    # ✅ Install GPU-enabled PyTorch directly from pip (CUDA 12.4 build)
    - torch==2.4.1+cu124
    - torchvision==0.19.1+cu124
    - torchaudio==2.4.1+cu124
    - --extra-index-url https://download.pytorch.org/whl/cu124

    - matplotlib
    - pandas
    - seaborn
    - ipywidgets
    - rich
    - scikit-learn
    - albumentations
    - opencv-python-headless
    - segmentation_models_pytorch
    - jupyter
    - shapely
    - opencv-python-headless
    - segmentation_models_pytorch
    - jupyter
    - shapely
